### ISSUE TITLE
add user authentification 

### ISSUE THREAD

**Issue by gl0bix** [gl0bix/de.itconsult24#6]

**Comment by sirhC-B** [comment]
Auth ist implementiert. 
Zum testen Customer in DB anlegen mit:

INSERT INTO `itconsult_customer` (`id`, `email`, `password`, `enabled`) VALUES
    (1, 'test@test.de', '{bcrypt}$2a$10$yJixZy/KbspjVj8USGV1O.OXDPxOiT2w2HXZMBRl6aGNDNK1QU2Yi', 1);


Login: /login

Email: <test@test.de>
Passwort: <geheim>

Erfolgskontrolle: /secure (wenn weiterleitung auf /secure dann erfolgreich | wenn auf startseite, dann nicht)

**Comment by sirhC-B** [comment]
Passwort ist "geheim"
